export interface VaccineResource {
  id: string;
  category: "general" | "schedules" | "safety";
  source: "MOH" | "WHO" | "UNICEF";
  title: { [key: string]: string };
  summary: { [key: string]: string };
  url: string;
  publishedDate?: string;
}

export const VACCINE_RESOURCES: VaccineResource[] = [
  {
    id: "moh-kenya-schedule-2024",
    category: "schedules",
    source: "MOH",
    title: {
      en: "Kenya National Immunization Schedule 2024",
      sw: "Ratiba ya Chanjo ya Kitaifa ya Kenya 2024",
      ki: "Ratiba ya Ithondeki ya Bururi wa Kenya 2024",
      luo: "Chenro mar Thurune mar Kenya 2024",
      kam: "Ratiba ya Ithonzeki ya Kenya 2024",
      luy: "Echisimikho chye Echindakwa chye Kenya 2024",
      kal: "Torosiek chebo Thurwenisiek chebo Kenya 2024",
    },
    summary: {
      en: "Complete vaccination schedule for children from birth to 18 years, including timing and recommended vaccines for each age group.",
      sw: "Ratiba kamili ya chanjo kwa watoto tangu kuzaliwa hadi miaka 18, ikijumuisha muda na chanjo zinazopendekeza kwa kila kikundi cha umri.",
      ki: "Ratiba ya ithondeki nĩ ũndũ wa ciana kuuma kũrĩ ciana nginya mĩaka 18, ikĩonania mahinda na ithondeki iria ciendekagĩrwo nĩ o gĩkundi kĩa mĩaka.",
      luo: "Chenro mar thurune duto ne nyithindo chakre onyuol nyaka higni 18, kaachiel gi kinde gi thurune ma iyiero ne kit higni ka kit higni.",
      kam: "Ratiba ya ithonzeki yoonthe nĩ ũndũ wa ciana kuuma kũzaawa ngĩka mĩaka 18, ĩkĩonania mahinda na ithonzeki ila syendekagĩlwa nĩ o kĩũngano kya mĩaka.",
      luy: "Echisimikho chyonakhe chye echindakwa kwe obwana khulawa khu okhusaalwa khukasa emyakha 18, nikhumanyikhanaa obulakho nende echindakwa chye khusimikha khu obukholo obundi.",
      kal: "Torosiek nebo asiis chebo thurwenisiek nebo lagok aeng kikutunyo ngot nebo kenyisiek 18, ak kochiny torowek ago thurwenisiek ne kimachei ak kenyisiek.",
    },
    url: "https://www.health.go.ke/immunization-schedule/",
    publishedDate: "2024",
  },
  {
    id: "who-vaccine-safety",
    category: "safety",
    source: "WHO",
    title: {
      en: "Vaccine Safety and Side Effects",
      sw: "Usalama wa Chanjo na Athari Zake",
      ki: "Ũtũmu wa Ithondeki na Mahĩtia Macio",
      luo: "Kwe mar Thurune gi Gik Maricho",
      kam: "Ũtũmu wa Ithonzeki na Mahĩtia Macio",
      luy: "Akhakha ka Echindakwa nende Ebirema",
      kal: "Tyend Kweit nebo Thurwenisiek ak Komi Nebo Rurok",
    },
    summary: {
      en: "Information about how vaccines are tested for safety, common side effects to expect, and when to seek medical help.",
      sw: "Habari kuhusu jinsi chanjo zinavyopimwa kwa usalama, athari za kawaida zinazotarajiwa, na wakati wa kutafuta msaada wa kimatibabu.",
      ki: "Ũhoro wa ũrĩa ithondeki inyituagwo nĩ ũndũ wa ũtũmu, mahĩtia ma kawaida ma kwĩhitĩrĩria, na rĩrĩa ũkwenda gũcaria ũteithio wa ũgima.",
      luo: "Weche kuom kaka thurune item kar kwe, gik maricho mag piny ma inyalo par, to sa ma idwaro kony mar ngʼiyo.",
      kam: "Ũhoro wa ũla ithonzeki nyĩtugwo nĩ ũndũ wa ũtũmu, mahĩtia ma kawaida ma kwĩhitĩlĩlia, na lĩlĩa ũkwenda gũethela ũteithio wa ũgima.",
      luy: "Ebindu khunakhana ne engeli echindakwa chiriaa khulonda akhakha, ebirema ebya obulalikhi ebyo okhwikholela, nende obulakho obwo okhukhwaa obulayi.",
      kal: "Tugul konebutab koikoldo thurwenisiek ak tyend kweit, komi nebo rurok ne ki ngalalei, ak torowek ne kiut tugul nebo ositwet.",
    },
    url: "https://www.who.int/news-room/questions-and-answers/item/vaccines-and-immunization-vaccine-safety",
    publishedDate: "2023",
  },
  {
    id: "unicef-immunization",
    category: "general",
    source: "UNICEF",
    title: {
      en: "Why Vaccines Matter: Protecting Children Worldwide",
      sw: "Kwa Nini Chanjo ni Muhimu: Kulinda Watoto Ulimwenguni Kote",
      ki: "Nĩkĩĩ Ithondeki Nĩ Cia Bata: Kũgitĩra Ciana Thĩ Yothe",
      luo: "Momiyo Thurune Ber: Rito Nyithindo e Piny Duto",
      kam: "Nĩkĩĩ Ithonzeki Nĩ Sya Bata: Kũgitĩla Ciana Thĩ Yothe",
      luy: "Nikhukhulwa Echindakwa Khulolanga: Khulinda Obwana Khwisi Khwonakhe",
      kal: "Ak Komi Ne Thurwenisiek Beek: Ritin Lagok Kainet Nebo Asiis",
    },
    summary: {
      en: "Learn how vaccines have saved millions of lives, prevented diseases, and continue to protect children from serious illnesses.",
      sw: "Jifunze jinsi chanjo zimehifadhi maisha ya mamilioni, kuzuia magonjwa, na kuendelea kulinda watoto dhidi ya magonjwa makubwa.",
      ki: "Ĩga ũrĩa ithondeki ihonokĩtie mĩoyo ya andũ mamilioni, kũgiria mĩrimũ, na gũthiĩ na mbere gũgitĩra ciana kuuma harĩ mĩrimũ mĩnene.",
      luo: "Puonjri kaka thurune osekonyo ji mamil, genyo tuoche, kendo siko rito nyithindo kuom tuoche malit.",
      kam: "Ĩga ũla ithonzeki yĩhonokĩtie mĩoyo ya andũ mamĩlioni, kũgila mĩlimũ, na gũthiĩ na mbele kũgitĩla ciana kuuma kalĩ ka mĩlimũ mĩnene.",
      luy: "Yikheni engeli echindakwa chiakamulile obulamu obwa abasacha, khurisia amalwale, nende khwendeleela khulinda obwana khulawa khu amalwale amakalali.",
      kal: "Ngalalech koikoldo thurwenisiek ki wok kochorsi ji milion, ritinin tuok, ak tinyei ritin lagok aeng tuok ne beek.",
    },
    url: "https://www.unicef.org/immunization",
    publishedDate: "2024",
  },
  {
    id: "moh-mmr-safety",
    category: "safety",
    source: "MOH",
    title: {
      en: "MMR Vaccine Safety Information",
      sw: "Habari za Usalama wa Chanjo ya MMR",
      ki: "Ũhoro wa Ũtũmu wa Ithondeki ya MMR",
      luo: "Weche Kwe mar Thurune mar MMR",
      kam: "Ũhoro wa Ũtũmu wa Ithonzeki ya MMR",
      luy: "Ebindu bye Akhakha ka Echindakwa chya MMR",
      kal: "Tugul nebo Tyend Kweit nebo Thurwenik nebo MMR",
    },
    summary: {
      en: "Detailed information about the MMR (Measles, Mumps, Rubella) vaccine, its safety profile, and protection it provides.",
      sw: "Habari za kina kuhusu chanjo ya MMR (Surua, Matotota, Rubella), usalama wake, na ulinzi unaotolewa.",
      ki: "Ũhoro wa ũkĩrĩrĩri wa ithondeki ya MMR (Hura, Matotota, Rubella), ũtũmu wayo, na ũgitĩri ũrĩa ĩkũheaga.",
      luo: "Weche matut kuom thurune mar MMR (Odhuol, Mumps, Rubella), kweye, gi rito ma ochiwo.",
      kam: "Ũhoro wa ũkĩlĩlĩ wa ithonzeki ya MMR (Hula, Matotota, Rubella), ũtũmu wayo, na ũgitĩli ũla ĩkũheaga.",
      luy: "Ebindu ebimenyekha obulalikhi khunakhana ne echindakwa chya MMR (Amasuria, Mumps, Rubella), akhakha kacho, nende akhakholela ako chakhekhaa.",
      kal: "Tugul ne ngalalei matut konebutab thurwenik nebo MMR (Ng'etit, Mumps, Rubella), tyend kweite, ak ritin ne kimiyi.",
    },
    url: "https://www.health.go.ke/mmr-vaccine/",
    publishedDate: "2024",
  },
  {
    id: "who-covid-vaccines",
    category: "general",
    source: "WHO",
    title: {
      en: "COVID-19 Vaccines: What You Need to Know",
      sw: "Chanjo za COVID-19: Unahitaji Kujua Nini",
      ki: "Ithondeki cia COVID-19: Ũrĩa Wabataire Kũmenya",
      luo: "Thurune mag COVID-19: Gima Idwaro ng'eyo",
      kam: "Ithonzeki sya COVID-19: Ũla Ũbataa Kũmenya",
      luy: "Echindakwa chya COVID-19: Echio Okhwetakha Okhumenya",
      kal: "Thurwenisiek chebo COVID-19: Ne Idwaro ng'alale",
    },
    summary: {
      en: "Current information about COVID-19 vaccines, their effectiveness, safety, and availability in Kenya.",
      sw: "Habari za sasa kuhusu chanjo za COVID-19, ufanisi wao, usalama, na upatikanaji nchini Kenya.",
      ki: "Ũhoro wa rĩu wa ithondeki cia COVID-19, wĩra wacio, ũtũmu, na ũonekani bururi wa Kenya.",
      luo: "Weche machon kuom thurune mag COVID-19, tichgi, kwe, gi yudore e Kenya.",
      kam: "Ũhoro wa lĩu wa ithonzeki sya COVID-19, wĩla wacio, ũtũmu, na ũonekani bululi wa Kenya.",
      luy: "Ebindu ebyo obulakhu khunakhana ne echindakwa chya COVID-19, obulayi bwacho, akhakha, nende okhubonesya khwisi khwa Kenya.",
      kal: "Tugul nebo saa ne kochiny konebutab thurwenisiek chebo COVID-19, tiyetap, tyend kweit, ak yotet aeng Kenya.",
    },
    url: "https://www.who.int/emergencies/diseases/novel-coronavirus-2019/covid-19-vaccines",
    publishedDate: "2024",
  },
  {
    id: "unicef-vaccine-myths",
    category: "general",
    source: "UNICEF",
    title: {
      en: "Common Vaccine Myths Debunked",
      sw: "Hadithi za Uongo za Chanjo Zilizoharibiwa",
      ki: "Ngano Cia Kwĩhoka Cia Ithondeki Cihũkĩtwo",
      luo: "Weche Miriambo Kuom Thurune Ma Oketi",
      kam: "Ngano Sya Kwĩhoka Sya Ithonzeki Syĩhũkĩtwe",
      luy: "Ebisimikho ebya Obulalikhi ebyo Echindakwa Ebyenyekhekhwa",
      kal: "Tugul Ne Ng'omomisiek Nebo Thurwenisiek Ne Ki Ngalalei Mising",
    },
    summary: {
      en: "Evidence-based answers to common misconceptions and myths about vaccines, helping families make informed decisions.",
      sw: "Majibu yanayotegemea ushahidi kwa dhana zisizo sahihi na hadithi za uongo kuhusu chanjo, kusaidia familia kufanya maamuzi yenye taarifa.",
      ki: "Macookio ma gũtegema ũira kũrĩ meciiria matarĩ ma ma na ngano cia ithondeki, gũteithia nyũmba gũthondeka mĩbango ĩrĩ na ũmenyo.",
      luo: "Dwoko moyier gi ranyisi ne paro marach gi weche miriambo kuom thurune, konyo jomoko timo yiero maler.",
      kam: "Macookio ma gũtegema ũila kũlĩ mecĩĩlio matali ma ma na ngano sya ithonzeki, kũteithia nyũmba gũthondeka mĩbango ĩlĩ na ũmenyo.",
      luy: "Ebisubusia ebyo okhwingikhanaa khu ebiresia khulonda emikalikho emitali emiremaa nende ebisimikho ebya obulalikhi khunakhana ne echindakwa, khukonia amaanda okhukora obukhetuli obulolekha.",
      kal: "Dwoko ne ki ngalalei ak ng'otet ne borurit ko ne paro ne matinye keny ak tugul nebo ng'omomisiek konebutab thurwenisiek, kongoi kot tieny koikoldo tuny ne beek.",
    },
    url: "https://www.unicef.org/immunization/vaccine-myths-debunked",
    publishedDate: "2023",
  },
];
